server:
  port: 8084
spring:
  application:
    name: servicer-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8083/eureka
  instance:
    prefer-ip-address: true #当其他服务获得地址时提供ip而不是hostname
    ip-address: 127.0.0.1 #指定自己的ip信息，不指定的话会自己寻找
