server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ljq?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1117
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: service-provider

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8083/eureka